project:
  type: website

website:
  title: "Computational Loops"
  navbar:
    right:
      - href: posts/optimization/listing.qmd
        text: Optimization Loops
      - href: about.qmd
        text: About
  page-footer:
    center:
      - text: "_License_"
        href: LICENSE.qmd

execute:
  freeze: auto

format:
  html:
    theme:
      light: [flatly, style/custom_light.scss]
      dark: [flatly, style/custom_dark.scss]
    mainfont: Crimson Text, serif
    fontsize: 18px
    smooth-scroll: true
    css: style/common_style.css
    toc: true
    html-math-method: katex
    header-includes: |
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&display=swap');
      </style>
